"""Add local lookup tables required by sync and exporter.

Revision ID: 0003
Create Date: 2026-04-15
"""

from __future__ import annotations

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS occupation_domain (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS occupation_domain_name (
            domain_id INTEGER NOT NULL REFERENCES occupation_domain(id) ON DELETE CASCADE,
            locale TEXT NOT NULL,
            name TEXT NOT NULL,
            is_display BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY (domain_id, locale, name)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_domname_display "
        "ON occupation_domain_name(domain_id, locale) WHERE is_display = true"
    )

    op.execute("""
        CREATE TABLE IF NOT EXISTS occupation (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE,
            parent_id INTEGER REFERENCES occupation(id),
            domain_id INTEGER REFERENCES occupation_domain(id)
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS occupation_name (
            occupation_id INTEGER NOT NULL REFERENCES occupation(id) ON DELETE CASCADE,
            locale TEXT NOT NULL,
            name TEXT NOT NULL,
            is_display BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY (occupation_id, locale, name)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_occname_display "
        "ON occupation_name(occupation_id, locale) WHERE is_display = true"
    )

    op.execute("""
        CREATE TABLE IF NOT EXISTS seniority (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS seniority_name (
            seniority_id INTEGER NOT NULL REFERENCES seniority(id) ON DELETE CASCADE,
            locale TEXT NOT NULL,
            name TEXT NOT NULL,
            is_display BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY (seniority_id, locale, name)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_senname_display "
        "ON seniority_name(seniority_id, locale) WHERE is_display = true"
    )

    op.execute("""
        CREATE TABLE IF NOT EXISTS technology (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE,
            name TEXT,
            category TEXT
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS industry (
            id SMALLINT PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS industry_name (
            industry_id SMALLINT NOT NULL REFERENCES industry(id) ON DELETE CASCADE,
            locale TEXT NOT NULL,
            name TEXT NOT NULL,
            is_display BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY (industry_id, locale, name)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_indname_display "
        "ON industry_name(industry_id, locale) WHERE is_display = true"
    )

    op.execute("""
        CREATE TABLE IF NOT EXISTS location (
            id INTEGER PRIMARY KEY,
            parent_id INTEGER REFERENCES location(id),
            type TEXT NOT NULL,
            population INTEGER,
            languages TEXT[]
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_loc_parent ON location(parent_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_loc_type ON location(type)")
    op.execute("""
        CREATE TABLE IF NOT EXISTS location_name (
            location_id INTEGER NOT NULL REFERENCES location(id) ON DELETE CASCADE,
            locale TEXT NOT NULL,
            name TEXT NOT NULL,
            is_display BOOLEAN NOT NULL DEFAULT false,
            PRIMARY KEY (location_id, locale, name)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_locname_display "
        "ON location_name(location_id, locale) WHERE is_display = true"
    )
    op.execute("""
        CREATE TABLE IF NOT EXISTS location_macro_member (
            macro_id INTEGER NOT NULL REFERENCES location(id) ON DELETE CASCADE,
            country_id INTEGER NOT NULL REFERENCES location(id) ON DELETE CASCADE,
            PRIMARY KEY (macro_id, country_id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS currency_rate (
            currency TEXT PRIMARY KEY,
            to_eur NUMERIC(10, 6) NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS taxonomy_miss (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            taxonomy TEXT NOT NULL,
            raw_value TEXT NOT NULL,
            sample_value TEXT NOT NULL,
            hit_count INTEGER NOT NULL DEFAULT 1,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            status TEXT NOT NULL DEFAULT 'pending',
            resolved_to TEXT
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_tm_taxonomy_raw "
        "ON taxonomy_miss(taxonomy, raw_value)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_tm_pending "
        "ON taxonomy_miss(taxonomy, hit_count) WHERE status = 'pending'"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS currency_rate")
    op.execute("DROP TABLE IF EXISTS location_macro_member")
    op.execute("DROP TABLE IF EXISTS location_name")
    op.execute("DROP TABLE IF EXISTS location")
    op.execute("DROP TABLE IF EXISTS taxonomy_miss")
    op.execute("DROP TABLE IF EXISTS industry_name")
    op.execute("DROP TABLE IF EXISTS industry")
    op.execute("DROP TABLE IF EXISTS technology")
    op.execute("DROP TABLE IF EXISTS seniority_name")
    op.execute("DROP TABLE IF EXISTS seniority")
    op.execute("DROP TABLE IF EXISTS occupation_name")
    op.execute("DROP TABLE IF EXISTS occupation")
    op.execute("DROP TABLE IF EXISTS occupation_domain_name")
    op.execute("DROP TABLE IF EXISTS occupation_domain")
