import { msg } from "@lingui/core/macro";

export const marketingMessages = {
  alerts_link: msg({ id: "marketing.alerts.link", comment: "Public marketing page: alerts_link", message: "Company job alerts" }),
  tracker_link: msg({ id: "marketing.tracker.link", comment: "Public marketing page: tracker_link", message: "Application tracker" }),
  guide_link: msg({ id: "marketing.guide.link", comment: "Public marketing page: guide_link", message: "How to monitor career pages" }),
  alerts_title: msg({ id: "marketing.alerts.title", comment: "Public marketing page: alerts_title", message: "Job alerts for the companies you choose" }),
  alerts_description: msg({ id: "marketing.alerts.description", comment: "Public marketing page: alerts_description", message: "Follow employers in one watchlist, filter their openings, and choose a weekly email digest of new matches. Start with a free company search." }),
  alerts_eyebrow: msg({ id: "marketing.alerts.eyebrow", comment: "Public marketing page: alerts_eyebrow", message: "Your next role starts with the right companies" }),
  alerts_body: msg({ id: "marketing.alerts.body", comment: "Public marketing page: alerts_body", message: "Get new matches from the companies you choose in one weekly email. Save your employers and filters as a watchlist—a saved job search you can revisit anytime." }),
  alerts_cta: msg({ id: "marketing.alerts.cta", comment: "Public marketing page: alerts_cta", message: "Find companies to follow" }),
  alerts_stepsTitle: msg({ id: "marketing.alerts.stepsTitle", comment: "Public marketing page: alerts_stepsTitle", message: "From a shortlist to a regular update" }),
  alerts_step1Title: msg({ id: "marketing.alerts.step1Title", comment: "Public marketing page: alerts_step1Title", message: "Choose your employers" }),
  alerts_step1Body: msg({ id: "marketing.alerts.step1Body", comment: "Public marketing page: alerts_step1Body", message: "Search for companies on Job Seek. Still building your shortlist? Start with a role and location. You can request a missing employer." }),
  alerts_step2Title: msg({ id: "marketing.alerts.step2Title", comment: "Public marketing page: alerts_step2Title", message: "Save your search as a watchlist" }),
  alerts_step2Body: msg({ id: "marketing.alerts.step2Body", comment: "Public marketing page: alerts_step2Body", message: "Combine companies with role, location, work mode, or salary filters. Sign in to save the search. Free accounts can keep up to 10 watchlists." }),
  alerts_step3Title: msg({ id: "marketing.alerts.step3Title", comment: "Public marketing page: alerts_step3Title", message: "Choose your weekly digest" }),
  alerts_step3Body: msg({ id: "marketing.alerts.step3Body", comment: "Public marketing page: alerts_step3Body", message: "Verify your email and enable your chosen watchlists in Settings. New matches are combined into one weekly digest of up to 20 roles. Pause emails whenever you need." }),
  alerts_scopeTitle: msg({ id: "marketing.alerts.scopeTitle", comment: "Public marketing page: alerts_scopeTitle", message: "A weekly digest. A feed you can revisit anytime." }),
  alerts_scopeBody: msg({ id: "marketing.alerts.scopeBody", comment: "Public marketing page: alerts_scopeBody", message: "Enable email for the watchlists you choose. New matches arrive together in one weekly digest of up to 20 roles. Revisit your saved search between emails, or pause notifications in Settings." }),
  alerts_proofTitle: msg({ id: "marketing.alerts.proofTitle", comment: "Public marketing page: alerts_proofTitle", message: "Your companies and filters, together" }),
  alerts_proofBody: msg({ id: "marketing.alerts.proofBody", comment: "Public marketing page: alerts_proofBody", message: "A watchlist can follow selected companies or search across employers. You stay in control of its filters and notification preferences." }),
  alerts_imageAlt: msg({ id: "marketing.alerts.imageAlt", comment: "Public marketing page: alerts_imageAlt", message: "Job Seek watchlist with companies and role filters" }),
  tracker_title: msg({ id: "marketing.tracker.title", comment: "Public marketing page: tracker_title", message: "Keep your applications in view" }),
  tracker_description: msg({ id: "marketing.tracker.description", comment: "Public marketing page: tracker_description", message: "A free application tracker for jobs saved on Job Seek. Organize roles, update application stages, and keep interview notes together." }),
  tracker_eyebrow: msg({ id: "marketing.tracker.eyebrow", comment: "Public marketing page: tracker_eyebrow", message: "Free job application tracker" }),
  tracker_body: msg({ id: "marketing.tracker.body", comment: "Public marketing page: tracker_body", message: "Save jobs you find on Job Seek, update their status as you apply, and keep interview notes together." }),
  tracker_cta: msg({ id: "marketing.tracker.cta", comment: "Public marketing page: tracker_cta", message: "Find a job to save" }),
  tracker_stepsTitle: msg({ id: "marketing.tracker.stepsTitle", comment: "Public marketing page: tracker_stepsTitle", message: "A place for each next step" }),
  tracker_step1Title: msg({ id: "marketing.tracker.step1Title", comment: "Public marketing page: tracker_step1Title", message: "Save a role" }),
  tracker_step1Body: msg({ id: "marketing.tracker.step1Body", comment: "Public marketing page: tracker_step1Body", message: "Find a job on Job Seek and save it to your account. Your saved roles stay together, ready for your next visit." }),
  tracker_step2Title: msg({ id: "marketing.tracker.step2Title", comment: "Public marketing page: tracker_step2Title", message: "Update its status" }),
  tracker_step2Body: msg({ id: "marketing.tracker.step2Body", comment: "Public marketing page: tracker_step2Body", message: "Mark a role as applied, interviewing, offered, or rejected. You update the status; Job Seek does not submit applications for you." }),
  tracker_step3Title: msg({ id: "marketing.tracker.step3Title", comment: "Public marketing page: tracker_step3Title", message: "Keep interview notes" }),
  tracker_step3Body: msg({ id: "marketing.tracker.step3Body", comment: "Public marketing page: tracker_step3Body", message: "Record each interview round with its date, type, and notes. See how your applications progress from saved roles to interviews and offers." }),
  tracker_scopeTitle: msg({ id: "marketing.tracker.scopeTitle", comment: "Public marketing page: tracker_scopeTitle", message: "Built for jobs you save on Job Seek" }),
  tracker_scopeBody: msg({ id: "marketing.tracker.scopeBody", comment: "Public marketing page: tracker_scopeBody", message: "The tracker follows jobs you save on Job Seek. Applications from other websites cannot be added. Apply on the employer’s website, then update your status here." }),
  tracker_proofTitle: msg({ id: "marketing.tracker.proofTitle", comment: "Public marketing page: tracker_proofTitle", message: "The role and its history, side by side" }),
  tracker_proofBody: msg({ id: "marketing.tracker.proofBody", comment: "Public marketing page: tracker_proofBody", message: "Return to the job details while you prepare for an interview. Your status and notes stay attached to the role you saved." }),
  tracker_imageAlt: msg({ id: "marketing.tracker.imageAlt", comment: "Public marketing page: tracker_imageAlt", message: "Job Seek saved role with application status and interview details" }),
  common_example: msg({ id: "marketing.common.example", comment: "Public marketing page: common_example", message: "Illustrative example" }),
  common_exampleCompany: msg({ id: "marketing.common.exampleCompany", comment: "Public marketing page: common_exampleCompany", message: "Example company" }),
  common_exampleRole: msg({ id: "marketing.common.exampleRole", comment: "Public marketing page: common_exampleRole", message: "Quality specialist" }),
  common_saved: msg({ id: "marketing.common.saved", comment: "Public marketing page: common_saved", message: "Saved" }),
  common_applied: msg({ id: "marketing.common.applied", comment: "Public marketing page: common_applied", message: "Applied" }),
  common_interview: msg({ id: "marketing.common.interview", comment: "Public marketing page: common_interview", message: "Interviewing" }),
  common_exampleNote: msg({ id: "marketing.common.exampleNote", comment: "Public marketing page: common_exampleNote", message: "Interview notes stay with the role." }),
  common_digestTitle: msg({ id: "marketing.common.digestTitle", comment: "Public marketing page: common_digestTitle", message: "Your weekly job matches" }),
  common_digestBody: msg({ id: "marketing.common.digestBody", comment: "Public marketing page: common_digestBody", message: "New matches from the watchlists you enabled." }),
  common_digestFooter: msg({ id: "marketing.common.digestFooter", comment: "Public marketing page: common_digestFooter", message: "One digest. Your chosen watchlists." }),
  common_free: msg({ id: "marketing.common.free", comment: "Public marketing page: common_free", message: "Free to use. Sign in to save your progress." }),
  common_continue: msg({ id: "marketing.common.continue", comment: "Public marketing page: common_continue", message: "Build a search you can come back to" }),
  common_related: msg({ id: "marketing.common.related", comment: "Public marketing page: common_related", message: "Find your next step" }),
  alerts_noShortlist: msg({ id: "marketing.alerts.noShortlist", comment: "Public marketing page: alerts_noShortlist", message: "No companies in mind? Start with a role and location." }),
  alerts_free: msg({ id: "marketing.alerts.free", comment: "Public marketing page: alerts_free", message: "Free search. Up to 10 watchlists. Opt-in weekly emails." }),
  common_enlarge: msg({ id: "marketing.common.enlarge", comment: "Public marketing page: common_enlarge", message: "Open full-size screenshot" }),
};
