app = 'jobseek'
primary_region = 'fra'
kill_timeout = 60

[processes]
  app = 'uv run --no-sync scheduler --http-only'

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
