/**
 * Namespaces overwhelmingly used by automated exploit probes. They cannot be
 * created by the current username flow and should never fall through to the
 * public watchlist resolver.
 */
const PROBE_USER_SLUGS = new Set([
  "adminer",
  "cgi-bin",
  "phpmyadmin",
  "wp-admin",
  "wp-content",
  "wp-includes",
  "wp-json",
  "xmlrpc",
]);

// Current usernames are lowercase, but accept uppercase here for legacy
// display_username rows. Watchlist slugs have always been generated by
// slugifyTitle and are therefore lowercase.
const USER_SLUG_RE = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i;
const WATCHLIST_SLUG_RE = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

/**
 * Cheap request-shape gate for the broad /:lang/:user/:watchlist route.
 *
 * This deliberately checks only invariants that valid persisted URLs already
 * satisfy. It rejects dotted filenames, encoded exploit paths, overlong
 * segments, and well-known scanner namespaces before Redis, Postgres,
 * Typesense, metadata, or OG rendering can run.
 */
export function isPlausiblePublicWatchlistPath(
  userSlug: string,
  watchlistSlug: string,
): boolean {
  if (userSlug.length < 3 || userSlug.length > 30) return false;
  if (watchlistSlug.length < 1 || watchlistSlug.length > 60) return false;
  if (!USER_SLUG_RE.test(userSlug)) return false;
  if (!WATCHLIST_SLUG_RE.test(watchlistSlug)) return false;
  return !PROBE_USER_SLUGS.has(userSlug.toLowerCase());
}
