"""Single-job monitor dispatcher.

Pure function — takes board config and HTTP client, returns discovered jobs.
No database awareness, no side effects beyond HTTP requests.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from dataclasses import replace as dataclass_replace
from pathlib import Path
from typing import TYPE_CHECKING
from urllib.parse import quote

import structlog

from src.core.monitors import (
    DiscoveredJob,
    get_discoverer,
    get_save_raw,
    get_stream_fn,
    validate_explicit_source_identity,
)

if TYPE_CHECKING:
    import httpx


@dataclass(slots=True)
class MonitorResult:
    """Result of monitoring a single board."""

    urls: set[str] = field(default_factory=set)
    jobs_by_url: dict[str, DiscoveredJob] | None = None
    new_sitemap_url: str | None = None
    filtered_count: int = 0
    # URLs rejected by an explicit provider-boundary allowlist. Unlike the
    # ordinary extraction filter (which commonly removes non-job sitemap
    # pages), any non-zero value is a security signal for one-shot migrations.
    security_filtered_count: int = 0
    #: Runtime proof that a zero result was produced by an authoritative
    #: currentness/empty-state contract rather than extraction drift. This is
    #: generated by monitor code, never accepted as free-form board config.
    verified_empty_reason: str | None = None
    #: JSONB patch to merge into ``job_board.metadata`` after a successful
    #: batch (e.g. incremental monitors use this to persist a high-water mark).
    metadata_updates: dict | None = None
    #: Set to True by hybrid monitors (e.g. eightfold) that provide rich data
    #: only for a subset of ``urls``. The pipeline uses this flag to skip the
    #: content-update path for "touched" jobs (which would otherwise overwrite
    #: previously-scraped fields with nulls from partial rich data).
    hybrid: bool = False
    #: Set to True when the monitor's discovery hit its ``MAX_JOBS`` cap and
    #: returned a truncated list (#3216). The pipeline treats the run as a
    #: partial success: it inserts the URLs that ARE in the batch but skips
    #: ``_MARK_GONE_BY_TIMESTAMP`` for the cycle, so the unseen tail beyond
    #: the cap is not falsely tombstoned. Any single truncated batch in a
    #: streamed monitor run is sufficient to flip this for the cycle.
    truncated: bool = False


_SOURCE_LOCALE_PREFERENCE = ("en", "de", "fr", "it")
_SOURCE_IDENTITY_FINGERPRINT_KEY = "source_identity_fingerprint"


def _publication_rank(job: DiscoveredJob) -> tuple[int, str, str]:
    """Choose one outbound publication independently of provider ordering."""
    language = (job.language or "").lower()
    try:
        locale_rank = _SOURCE_LOCALE_PREFERENCE.index(language)
    except ValueError:
        locale_rank = len(_SOURCE_LOCALE_PREFERENCE)
    return locale_rank, language, job.url


def _identity_fingerprint(job: DiscoveredJob) -> str | None:
    value = (
        job.metadata.get(_SOURCE_IDENTITY_FINGERPRINT_KEY)
        if isinstance(job.metadata, dict)
        else None
    )
    if value is None:
        return None
    if not isinstance(value, str) or not value or len(value) > 256:
        raise ValueError("source_identity_fingerprint must be non-empty bounded text when provided")
    return value


def _merge_publication_localizations(jobs: list[DiscoveredJob]) -> dict | None:
    """Retain all locale content while selecting one outbound publication."""
    merged: dict = {}
    for job in sorted(jobs, key=_publication_rank):
        for locale, payload in (job.localizations or {}).items():
            if locale in merged and merged[locale] != payload:
                raise ValueError(
                    "source_identity publications emitted conflicting localization payloads"
                )
            merged[locale] = payload
        if job.language:
            payload = {
                key: value
                for key, value in (
                    ("title", job.title),
                    ("description", job.description),
                    ("locations", job.locations),
                )
                if value is not None
            }
            if payload:
                existing = merged.get(job.language)
                if existing is not None and existing != payload:
                    raise ValueError(
                        "source_identity publications emitted conflicting content for one locale"
                    )
                merged[job.language] = payload
    return merged or None


def _collapse_source_identity_publications(
    discovered: list[DiscoveredJob],
) -> list[DiscoveredJob]:
    """Collapse locale publications only with exact provider evidence.

    A single explicit-identity row needs no extra proof.  Multiple rows with
    the same identity must all carry the same provider-derived fingerprint;
    otherwise a reused/colliding provider id fails the whole monitor cycle.
    The fixed locale order and URL tie-break make selection independent of API
    order and hash randomization.  Removing the preferred locale merely picks
    the next publication while retaining the same durable identity.
    """
    implicit: list[DiscoveredJob] = []
    grouped: dict[str, list[DiscoveredJob]] = {}
    for job in discovered:
        if job.source_identity is None:
            implicit.append(job)
            continue
        identity = validate_explicit_source_identity(job.source_identity)
        grouped.setdefault(identity, []).append(job)

    collapsed = list(implicit)
    for identity in sorted(grouped):
        publications = grouped[identity]
        if len(publications) > 1:
            fingerprints = [_identity_fingerprint(job) for job in publications]
            if any(value is None for value in fingerprints) or len(set(fingerprints)) != 1:
                raise ValueError(
                    "duplicate source_identity publications require one matching "
                    "source_identity_fingerprint"
                )
        selected = min(publications, key=_publication_rank)
        collapsed.append(
            dataclass_replace(
                selected,
                source_identity=identity,
                localizations=_merge_publication_localizations(publications),
            )
        )
    return collapsed


@dataclass(frozen=True, slots=True)
class _UrlTransformCollisionConfig:
    """Validated deterministic policy for intentional many-to-one URL transforms."""

    preferred_source_patterns: tuple[re.Pattern[str], ...]
    preferred_metadata_key: str | None
    preferred_metadata_patterns: tuple[re.Pattern[str], ...]
    canonical_identity_pattern: re.Pattern[str]
    identity_metadata_key: str | None
    source_identity_pattern: re.Pattern[str] | None
    stream_buffer_limit: int


def _url_transform_collision_config(
    config: dict,
) -> _UrlTransformCollisionConfig | None:
    """Validate the opt-in cross-batch collision policy."""
    transform = config.get("url_transform")
    if not isinstance(transform, dict):
        return None
    policy = transform.get("collision_policy")
    if policy is None:
        return None
    if policy != "prefer_source_pattern":
        raise ValueError("url_transform.collision_policy must be 'prefer_source_pattern'")

    raw_patterns = transform.get("collision_preferred_source_patterns")
    if (
        not isinstance(raw_patterns, list)
        or not raw_patterns
        or len(raw_patterns) > 32
        or any(
            not isinstance(pattern, str) or not pattern or len(pattern) > 2_048
            for pattern in raw_patterns
        )
    ):
        raise ValueError(
            "url_transform.collision_preferred_source_patterns must be a "
            "non-empty bounded regex list"
        )
    try:
        preferred_patterns = tuple(re.compile(pattern) for pattern in raw_patterns)
    except re.error as exc:
        raise ValueError(f"url_transform collision source pattern is invalid: {exc}") from exc

    preferred_metadata_key = transform.get("collision_preferred_metadata_key")
    raw_metadata_patterns = transform.get("collision_preferred_metadata_patterns")
    if (preferred_metadata_key is None) != (raw_metadata_patterns is None):
        raise ValueError(
            "url_transform collision metadata preference requires both a key and patterns"
        )
    if preferred_metadata_key is not None and (
        not isinstance(preferred_metadata_key, str)
        or not preferred_metadata_key
        or len(preferred_metadata_key) > 128
    ):
        raise ValueError(
            "url_transform.collision_preferred_metadata_key must be non-empty bounded text"
        )
    if raw_metadata_patterns is None:
        preferred_metadata_patterns: tuple[re.Pattern[str], ...] = ()
    else:
        if (
            not isinstance(raw_metadata_patterns, list)
            or not raw_metadata_patterns
            or len(raw_metadata_patterns) > 32
            or any(
                not isinstance(pattern, str) or not pattern or len(pattern) > 2_048
                for pattern in raw_metadata_patterns
            )
        ):
            raise ValueError(
                "url_transform.collision_preferred_metadata_patterns must be a "
                "non-empty bounded regex list"
            )
        try:
            preferred_metadata_patterns = tuple(
                re.compile(pattern) for pattern in raw_metadata_patterns
            )
        except re.error as exc:
            raise ValueError(f"url_transform collision metadata pattern is invalid: {exc}") from exc

    raw_identity_pattern = transform.get("collision_canonical_identity_regex")
    if (
        not isinstance(raw_identity_pattern, str)
        or not raw_identity_pattern
        or len(raw_identity_pattern) > 2_048
    ):
        raise ValueError(
            "url_transform.collision_canonical_identity_regex must be a non-empty bounded regex"
        )
    try:
        identity_pattern = re.compile(raw_identity_pattern)
    except re.error as exc:
        raise ValueError(
            f"url_transform collision canonical identity regex is invalid: {exc}"
        ) from exc
    if identity_pattern.groups != 1:
        raise ValueError(
            "url_transform.collision_canonical_identity_regex must contain "
            "exactly one capture group"
        )

    identity_metadata_key = transform.get("collision_identity_metadata_key")
    raw_source_identity_pattern = transform.get("collision_source_identity_regex")
    if (identity_metadata_key is None) == (raw_source_identity_pattern is None):
        raise ValueError(
            "url_transform collision identity requires exactly one metadata key or source regex"
        )
    if identity_metadata_key is not None and (
        not isinstance(identity_metadata_key, str)
        or not identity_metadata_key
        or len(identity_metadata_key) > 128
    ):
        raise ValueError(
            "url_transform.collision_identity_metadata_key must be non-empty bounded text"
        )
    source_identity_pattern: re.Pattern[str] | None = None
    if raw_source_identity_pattern is not None:
        if (
            not isinstance(raw_source_identity_pattern, str)
            or not raw_source_identity_pattern
            or len(raw_source_identity_pattern) > 2_048
        ):
            raise ValueError(
                "url_transform.collision_source_identity_regex must be a non-empty bounded regex"
            )
        try:
            source_identity_pattern = re.compile(raw_source_identity_pattern)
        except re.error as exc:
            raise ValueError(
                f"url_transform collision source identity regex is invalid: {exc}"
            ) from exc
        if source_identity_pattern.groups != 1:
            raise ValueError(
                "url_transform.collision_source_identity_regex must contain "
                "exactly one capture group"
            )
    stream_buffer_limit = transform.get("collision_stream_buffer_limit")
    if (
        not isinstance(stream_buffer_limit, int)
        or isinstance(stream_buffer_limit, bool)
        or not 1 <= stream_buffer_limit <= 50_000
    ):
        raise ValueError(
            "url_transform.collision_stream_buffer_limit must be an integer from 1 to 50000"
        )
    return _UrlTransformCollisionConfig(
        preferred_source_patterns=preferred_patterns,
        preferred_metadata_key=preferred_metadata_key,
        preferred_metadata_patterns=preferred_metadata_patterns,
        canonical_identity_pattern=identity_pattern,
        identity_metadata_key=identity_metadata_key,
        source_identity_pattern=source_identity_pattern,
        stream_buffer_limit=stream_buffer_limit,
    )


def _collision_source_rank(
    job: DiscoveredJob,
    source_url: str,
    collision: _UrlTransformCollisionConfig,
) -> tuple[int, int, str]:
    """Rank aliases by locale metadata, source preference, then source URL."""
    metadata_value = (
        job.metadata.get(collision.preferred_metadata_key)
        if isinstance(job.metadata, dict) and collision.preferred_metadata_key is not None
        else None
    )
    metadata_preference = next(
        (
            index
            for index, pattern in enumerate(collision.preferred_metadata_patterns)
            if isinstance(metadata_value, str) and pattern.search(metadata_value)
        ),
        len(collision.preferred_metadata_patterns),
    )
    source_preference = next(
        (
            index
            for index, pattern in enumerate(collision.preferred_source_patterns)
            if pattern.search(source_url)
        ),
        len(collision.preferred_source_patterns),
    )
    return metadata_preference, source_preference, source_url


def _validate_collision_identity(
    job: DiscoveredJob,
    source_url: str,
    canonical_url: str,
    collision: _UrlTransformCollisionConfig,
) -> None:
    """Require a rich provider identity to authenticate the transformed URL."""
    match = collision.canonical_identity_pattern.fullmatch(canonical_url)
    if collision.source_identity_pattern is not None:
        source_match = collision.source_identity_pattern.fullmatch(source_url)
        provider_identity = source_match.group(1) if source_match is not None else None
    else:
        provider_identity = (
            job.metadata.get(collision.identity_metadata_key)
            if isinstance(job.metadata, dict) and collision.identity_metadata_key is not None
            else None
        )
    if (
        match is None
        or not isinstance(provider_identity, str)
        or provider_identity != match.group(1)
    ):
        raise ValueError("url_transform collision provider identity does not match canonical URL")


def _normalize_discovered(
    discovered,
    *,
    reject_conflicting_duplicate_urls: bool = False,
) -> MonitorResult:
    """Normalize discover results into a MonitorResult.

    Sitemap returns (set[str], str | None).
    Rich monitors return list[DiscoveredJob].
    URL-only monitors return set[str].
    Hybrid monitors pre-build and return a MonitorResult directly.
    """
    if isinstance(discovered, MonitorResult):
        return discovered
    if isinstance(discovered, tuple):
        urls, sitemap_url = discovered
        return MonitorResult(urls=urls, new_sitemap_url=sitemap_url)
    if isinstance(discovered, set):
        return MonitorResult(urls=discovered)
    # list[DiscoveredJob]. Explicit provider identities may have several
    # locale publications, but only after a provider fingerprint proves that
    # the rows are the same exact job.
    discovered = _collapse_source_identity_publications(discovered)
    jobs_by_url: dict[str, DiscoveredJob] = {}
    for job in discovered:
        existing = jobs_by_url.get(job.url)
        if reject_conflicting_duplicate_urls and existing is not None and existing != job:
            raise ValueError(
                "url_transform collision batch emitted conflicting content "
                f"for source URL {job.url}"
            )
        jobs_by_url[job.url] = job
    return MonitorResult(urls=set(jobs_by_url), jobs_by_url=jobs_by_url)


def _apply_url_filter(result: MonitorResult, config: dict) -> MonitorResult:
    """Filter URLs using url_filter from config. Returns new MonitorResult."""
    raw_filter = config.get("url_filter")
    if not raw_filter:
        return result

    if isinstance(raw_filter, str):
        include, exclude = raw_filter, None
    else:
        include = raw_filter.get("include")
        exclude = raw_filter.get("exclude")

    try:
        include_re = re.compile(include) if include else None
        exclude_re = re.compile(exclude) if exclude else None
    except re.error as e:
        structlog.get_logger().warning("monitor.url_filter_invalid", error=str(e))
        return result

    filtered_urls = set()
    for url in result.urls:
        if include_re and not include_re.search(url):
            continue
        if exclude_re and exclude_re.search(url):
            continue
        filtered_urls.add(url)

    filtered_jobs = None
    if result.jobs_by_url is not None:
        filtered_jobs = {u: j for u, j in result.jobs_by_url.items() if u in filtered_urls}

    removed = len(result.urls) - len(filtered_urls)
    return MonitorResult(
        urls=filtered_urls,
        jobs_by_url=filtered_jobs,
        new_sitemap_url=result.new_sitemap_url,
        filtered_count=result.filtered_count + removed,
        security_filtered_count=result.security_filtered_count,
        verified_empty_reason=result.verified_empty_reason,
        metadata_updates=result.metadata_updates,
        hybrid=result.hybrid,
        truncated=result.truncated,
    )


def _apply_job_filter(result: MonitorResult, config: dict) -> MonitorResult:
    """Filter rich jobs by regexes over their discovered content.

    ``job_filter`` accepts the same string or ``{include, exclude}`` shape as
    ``url_filter``.  The searchable text contains the title, description,
    locations, and metadata.  A mapping may select one rich field via
    ``field``.  ``require_classification`` fails closed unless each job
    matches exactly one of the include/exclude expressions.  URL-only
    monitors cannot apply this filter and are left unchanged with a warning.
    """
    raw_filter = config.get("job_filter")
    if not raw_filter:
        return result

    if result.jobs_by_url is None:
        structlog.get_logger().warning("monitor.job_filter_unavailable")
        return result

    if isinstance(raw_filter, str):
        include, exclude = raw_filter, None
        filter_field = None
        require_classification = False
    else:
        include = raw_filter.get("include")
        exclude = raw_filter.get("exclude")
        filter_field = raw_filter.get("field")
        require_classification = raw_filter.get("require_classification", False)

    if not isinstance(require_classification, bool):
        raise ValueError("monitor job_filter require_classification must be a boolean")
    if require_classification and (not include or not exclude):
        raise ValueError(
            "monitor job_filter require_classification needs include and exclude regexes"
        )

    valid_fields = {None, "title", "description", "locations", "metadata"}
    if filter_field not in valid_fields and not (
        isinstance(filter_field, str) and filter_field.startswith("metadata.")
    ):
        if require_classification:
            raise ValueError(
                f"monitor job_filter has invalid classification field: {filter_field!r}"
            )
        structlog.get_logger().warning("monitor.job_filter_invalid_field", field=filter_field)
        return result

    try:
        include_re = re.compile(include) if include else None
        exclude_re = re.compile(exclude) if exclude else None
    except re.error as e:
        if require_classification:
            raise ValueError(f"monitor job_filter classification regex is invalid: {e}") from e
        structlog.get_logger().warning("monitor.job_filter_invalid", error=str(e))
        return result

    filtered_jobs: dict[str, DiscoveredJob] = {}
    for url, job in result.jobs_by_url.items():
        metadata = job.metadata or {}
        if filter_field == "title":
            content = job.title or ""
        elif filter_field == "description":
            content = job.description or ""
        elif filter_field == "locations":
            content = "\n".join(job.locations or [])
        elif filter_field == "metadata":
            content = json.dumps(metadata, ensure_ascii=False, sort_keys=True)
        elif isinstance(filter_field, str):
            value = metadata.get(filter_field.removeprefix("metadata."))
            content = (
                value
                if isinstance(value, str)
                else json.dumps(value, ensure_ascii=False, sort_keys=True)
                if value is not None
                else ""
            )
        else:
            content = "\n".join(
                part
                for part in (
                    job.title,
                    job.description,
                    "\n".join(job.locations or []),
                    json.dumps(metadata, ensure_ascii=False, sort_keys=True) if metadata else None,
                )
                if part
            )

        include_match = bool(include_re and include_re.search(content))
        exclude_match = bool(exclude_re and exclude_re.search(content))
        if require_classification:
            if include_match == exclude_match:
                classification = (
                    "both include and exclude" if include_match else "neither include nor exclude"
                )
                raise ValueError(
                    f"monitor job_filter require_classification matched {classification} for {url}"
                )
            if exclude_match:
                continue
        else:
            if include_re and not include_match:
                continue
            if exclude_match:
                continue
        filtered_jobs[url] = job

    # Hybrid monitors may carry URL-only entries alongside their rich subset.
    # Those entries have no content to evaluate, so preserve them fail-open.
    url_only = result.urls - result.jobs_by_url.keys()
    filtered_urls = url_only | (result.urls & filtered_jobs.keys())
    removed = len(result.urls) - len(filtered_urls)
    return MonitorResult(
        urls=filtered_urls,
        jobs_by_url=filtered_jobs,
        new_sitemap_url=result.new_sitemap_url,
        filtered_count=result.filtered_count + removed,
        security_filtered_count=result.security_filtered_count,
        verified_empty_reason=result.verified_empty_reason,
        metadata_updates=result.metadata_updates,
        hybrid=result.hybrid,
        truncated=result.truncated,
    )


def _apply_url_allowlist(result: MonitorResult, config: dict) -> MonitorResult:
    """Apply an exact, fail-closed provider-boundary URL allowlist.

    ``url_filter`` remains the broad extraction mechanism and intentionally
    fails open on malformed operator regexes for backward compatibility.
    ``url_allowlist`` is for security-sensitive identity transforms: it is a
    single regex evaluated with ``fullmatch`` and rejects every URL when the
    configured contract is empty, non-string, or invalid.
    """
    if "url_allowlist" not in config:
        return result

    raw_allowlist = config.get("url_allowlist")
    try:
        if not isinstance(raw_allowlist, str) or not raw_allowlist:
            raise ValueError("url_allowlist must be a non-empty regex string")
        pattern = re.compile(raw_allowlist)
    except (ValueError, re.error) as exc:
        structlog.get_logger().warning("monitor.url_allowlist_invalid", error=str(exc))
        return MonitorResult(
            urls=set(),
            jobs_by_url={} if result.jobs_by_url is not None else None,
            new_sitemap_url=result.new_sitemap_url,
            filtered_count=result.filtered_count,
            security_filtered_count=result.security_filtered_count + len(result.urls),
            verified_empty_reason=result.verified_empty_reason,
            metadata_updates=result.metadata_updates,
            hybrid=result.hybrid,
            truncated=result.truncated,
        )

    filtered_urls = {url for url in result.urls if pattern.fullmatch(url)}
    filtered_jobs = None
    if result.jobs_by_url is not None:
        filtered_jobs = {
            url: job for url, job in result.jobs_by_url.items() if url in filtered_urls
        }

    return MonitorResult(
        urls=filtered_urls,
        jobs_by_url=filtered_jobs,
        new_sitemap_url=result.new_sitemap_url,
        filtered_count=result.filtered_count,
        security_filtered_count=(
            result.security_filtered_count + len(result.urls) - len(filtered_urls)
        ),
        verified_empty_reason=result.verified_empty_reason,
        metadata_updates=result.metadata_updates,
        hybrid=result.hybrid,
        truncated=result.truncated,
    )


def _apply_url_transform(result: MonitorResult, config: dict) -> MonitorResult:
    """Rewrite URLs using ``url_transform`` from config.

    Collision transforms may put ``{identity}`` in ``replace``.  The marker
    is filled from the already validated collision identity metadata field,
    allowing localized provider URLs to collapse onto one stable provider-ID
    URL even when that identity is not present in the source URL.
    """
    transform = config.get("url_transform")
    if not transform:
        return result
    find = transform.get("find", "")
    replace = transform.get("replace", "")
    if not find:
        return result

    try:
        pattern = re.compile(find)
    except re.error as e:
        structlog.get_logger().warning("monitor.url_transform_invalid", error=str(e))
        return result
    collision = _url_transform_collision_config(config)
    identity_replacement = "{identity}" in replace
    if identity_replacement:
        if replace.count("{identity}") != 1:
            raise ValueError("url_transform.replace must contain at most one {identity} marker")
        if collision is None:
            raise ValueError(
                "url_transform.replace {identity} requires an intentional collision policy"
            )
        if result.jobs_by_url is None:
            raise ValueError("url_transform.replace {identity} requires rich discovered jobs")

    new_urls: set[str] = set()
    url_map: dict[str, str] = {}  # old -> new
    for url in sorted(result.urls):
        replacement = replace
        if identity_replacement:
            job = result.jobs_by_url.get(url) if result.jobs_by_url is not None else None
            identity = (
                job.metadata.get(collision.identity_metadata_key)
                if job is not None and isinstance(job.metadata, dict) and collision is not None
                else None
            )
            if not isinstance(identity, str) or not identity:
                raise ValueError("url_transform.replace {identity} metadata is missing or invalid")
            replacement = replace.replace("{identity}", quote(identity, safe=""))
        new_url = pattern.sub(replacement, url)
        new_urls.add(new_url)
        url_map[url] = new_url

    new_jobs = None
    if result.jobs_by_url is not None:
        if collision is None:
            new_jobs = {}
            for old_url, job in result.jobs_by_url.items():
                new_url = url_map.get(old_url, old_url)
                job.url = new_url
                new_jobs[new_url] = job
        else:
            selected: dict[
                str,
                tuple[tuple[int, int, str], DiscoveredJob, str | None],
            ] = {}
            for old_url in sorted(result.jobs_by_url):
                job = result.jobs_by_url[old_url]
                new_url = url_map.get(old_url, old_url)
                _validate_collision_identity(job, old_url, new_url, collision)
                rank = _collision_source_rank(job, old_url, collision)
                existing = selected.get(new_url)
                if existing is None:
                    selected[new_url] = (rank, job, job.source_identity)
                    continue
                existing_identity = existing[2]
                if (
                    existing_identity is not None
                    and job.source_identity is not None
                    and existing_identity != job.source_identity
                ):
                    raise ValueError(
                        "url_transform collision aliases have conflicting source identities"
                    )
                source_identity = existing_identity or job.source_identity
                if rank < existing[0]:
                    selected[new_url] = (rank, job, source_identity)
                elif source_identity != existing_identity:
                    selected[new_url] = (existing[0], existing[1], source_identity)
            new_jobs = {
                new_url: dataclass_replace(
                    selected_job,
                    url=new_url,
                    source_identity=source_identity,
                )
                for new_url, (_rank, selected_job, source_identity) in selected.items()
            }

    return MonitorResult(
        urls=new_urls,
        jobs_by_url=new_jobs,
        new_sitemap_url=result.new_sitemap_url,
        filtered_count=result.filtered_count,
        security_filtered_count=result.security_filtered_count,
        verified_empty_reason=result.verified_empty_reason,
        metadata_updates=result.metadata_updates,
        hybrid=result.hybrid,
        truncated=result.truncated,
    )


def _merge_collision_stream_result(
    buffered: MonitorResult | None,
    result: MonitorResult,
    collision: _UrlTransformCollisionConfig,
) -> MonitorResult:
    """Accumulate an intentional many-to-one transform across stream batches."""
    if buffered is None:
        buffered = MonitorResult(
            jobs_by_url={} if result.jobs_by_url is not None else None,
        )
    elif (buffered.jobs_by_url is None) != (result.jobs_by_url is None):
        raise ValueError("url_transform collision buffering cannot mix rich and URL-only batches")

    combined_urls = buffered.urls | result.urls
    if len(combined_urls) > collision.stream_buffer_limit:
        raise ValueError(
            "url_transform collision stream exceeded configured buffer limit "
            f"({len(combined_urls)} > {collision.stream_buffer_limit})"
        )
    buffered.urls = combined_urls

    if buffered.jobs_by_url is not None and result.jobs_by_url is not None:
        for source_url, job in result.jobs_by_url.items():
            existing = buffered.jobs_by_url.get(source_url)
            if existing is not None and existing != job:
                raise ValueError(
                    "url_transform collision stream emitted conflicting content "
                    f"for source URL {source_url}"
                )
            buffered.jobs_by_url[source_url] = job

    if result.new_sitemap_url is not None:
        if (
            buffered.new_sitemap_url is not None
            and buffered.new_sitemap_url != result.new_sitemap_url
        ):
            raise ValueError("url_transform collision stream emitted conflicting sitemap URLs")
        buffered.new_sitemap_url = result.new_sitemap_url
    if result.metadata_updates:
        metadata_updates = dict(buffered.metadata_updates or {})
        for key, value in result.metadata_updates.items():
            if key in metadata_updates and metadata_updates[key] != value:
                raise ValueError(
                    f"url_transform collision stream emitted conflicting metadata for key {key}"
                )
            metadata_updates[key] = value
        buffered.metadata_updates = metadata_updates

    buffered.filtered_count += result.filtered_count
    buffered.security_filtered_count += result.security_filtered_count
    if result.verified_empty_reason is not None:
        if (
            buffered.verified_empty_reason is not None
            and buffered.verified_empty_reason != result.verified_empty_reason
        ):
            raise ValueError("stream emitted conflicting verified-empty reasons")
        buffered.verified_empty_reason = result.verified_empty_reason
    buffered.hybrid = buffered.hybrid or result.hybrid
    buffered.truncated = buffered.truncated or result.truncated
    return buffered


async def _save_raw(
    artifact_dir: Path,
    board_url: str,
    monitor_type: str,
    monitor_config: dict,
    http: httpx.AsyncClient,
) -> None:
    """Fetch and save raw monitor source data to *artifact_dir*.

    Called after the main discover pass.  The extra fetch is cheap (single
    HTTP request) and only happens during interactive workspace runs.
    """
    save_raw = get_save_raw(monitor_type)
    if save_raw is None:
        return

    try:
        await save_raw(artifact_dir, board_url, monitor_config, http)
    except Exception:
        structlog.get_logger().warning(
            "monitor.save_raw_failed",
            monitor_type=monitor_type,
            board_url=board_url,
            exc_info=True,
        )


async def monitor_one(
    board_url: str,
    monitor_type: str,
    monitor_config: dict | None,
    http: httpx.AsyncClient,
    artifact_dir: Path | None = None,
    pw=None,
) -> MonitorResult:
    """Discover jobs on one board.

    This is the single-job layer — a pure function with no DB awareness.

    When *artifact_dir* is provided (workspace runs), raw source data
    (sitemap XML, API JSON, __NEXT_DATA__) is saved there for debugging.

    When *pw* is provided (an ``AsyncPlaywright`` instance), it is forwarded
    to the discover function to reuse a shared browser process.
    """
    discoverer = get_discoverer(monitor_type)
    config = monitor_config or {}
    collision = _url_transform_collision_config(config)

    # Build the board dict expected by discover functions
    board = {
        "board_url": board_url,
        "metadata": config,
    }

    from src.shared.http import client_for

    async with client_for(http, config) as client:
        discovered = await discoverer(board, client, pw=pw)
    result = _normalize_discovered(
        discovered,
        reject_conflicting_duplicate_urls=collision is not None,
    )
    before_filter = len(result.urls)
    result = _apply_url_filter(result, config)
    url_removed = before_filter - len(result.urls)
    if url_removed:
        structlog.get_logger().info(
            "monitor.url_filter",
            kept=len(result.urls),
            removed=url_removed,
        )
    before_filter = len(result.urls)
    result = _apply_job_filter(result, config)
    job_removed = before_filter - len(result.urls)
    if job_removed:
        structlog.get_logger().info(
            "monitor.job_filter",
            kept=len(result.urls),
            removed=job_removed,
        )
    before_allowlist = len(result.urls)
    result = _apply_url_allowlist(result, config)
    allowlist_removed = before_allowlist - len(result.urls)
    if allowlist_removed:
        structlog.get_logger().warning(
            "monitor.url_allowlist_rejected",
            kept=len(result.urls),
            removed=allowlist_removed,
        )
    result = _apply_url_transform(result, config)

    if artifact_dir is not None:
        artifact_dir.mkdir(parents=True, exist_ok=True)
        await _save_raw(artifact_dir, board_url, monitor_type, config, http)

    return result


async def monitor_one_stream(
    board_url: str,
    monitor_type: str,
    monitor_config: dict | None,
    http: httpx.AsyncClient,
    *,
    pw=None,
):
    """Async generator yielding MonitorResult per batch."""
    stream_fn = get_stream_fn(monitor_type)
    config = monitor_config or {}
    collision = _url_transform_collision_config(config)

    if stream_fn is None:
        yield await monitor_one(board_url, monitor_type, monitor_config, http, pw=pw)
        return

    board = {"board_url": board_url, "metadata": config}
    from src.shared.http import client_for

    buffered: MonitorResult | None = None
    async with client_for(http, config) as client:
        async for batch in stream_fn(board, client, pw=pw):
            result = _normalize_discovered(
                batch,
                reject_conflicting_duplicate_urls=collision is not None,
            )
            result = _apply_url_filter(result, config)
            result = _apply_job_filter(result, config)
            result = _apply_url_allowlist(result, config)
            if collision is not None:
                buffered = _merge_collision_stream_result(
                    buffered,
                    result,
                    collision,
                )
            else:
                result = _apply_url_transform(result, config)
                yield result
    if buffered is not None:
        yield _apply_url_transform(buffered, config)
